### ISSUE TITLE
Elasticsearch, kibana constantly restarting

### ISSUE THREAD

**Issue by caotangdaiduong** [sherifabdlnaby/elastdocker#19] opened 2020-08-05 04:22 UTC
I have tried to initialize many times with the available configurations, only changing the password. However, it still failed to reboot the container

![tempsnip](https://user-images.githubusercontent.com/28684084/89371490-ba65c580-d70d-11ea-913f-47ae704b7ddc.png)

**Comment by sherifabdlnaby** [comment] 2020-08-05 18:13
Please use `docker logs` and inspect Elasticsearch logs and post what it says.
Also, since you're using CentOS, please check #18 and see if it helps.

**Comment by caotangdaiduong** [comment] 2020-08-06 01:22
firewall-cmd --zone=public --add-masquerade --permanent
firewall-cmd --reload
[putty.log](https://github.com/sherifabdlnaby/elastdocker/files/5031974/putty.log)

**Comment by caotangdaiduong** [comment] 2020-08-06 01:26
I have tried with your case:
firewall-cmd --zone=public --add-masquerade --permanent
firewall-cmd --reload
firewall-cmd --zone=trusted --add-interface=docker0 --permanent
firewall-cmd --reload
**And check log:**
make logs
docker logs 17bd1e1102e1 [elastic_elasticsearch_1]
docker logs efc98748928c [elastic_kibana_1]
Pls check
[putty.log](https://github.com/sherifabdlnaby/elastdocker/files/5031992/putty.log)

**Comment by sherifabdlnaby** [comment] 2020-08-06 16:54
Elasticsearch failed the bootstrap checks 
```
elasticsearch_1           | ERROR: [1] bootstrap checks failed
elasticsearch_1           | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

Run this command your Docker's host to increase `vm.max_map_count`
```
sudo sysctl -w vm.max_map_count=262144
```

**Comment by sherifabdlnaby** [comment] 2020-08-06 16:55
Please confirm it was fixed and close the issue as this note was mentioned at the README, so no updates from my side needs to be done.

**Comment by caotangdaiduong** [comment] 2020-08-07 04:11
Hi, error with kibana, please check below:
![image](https://user-images.githubusercontent.com/28684084/89608212-b87f3c00-d89e-11ea-837e-652808064e40.png)
[putty v2.log](https://github.com/sherifabdlnaby/elastdocker/files/5039257/putty.v2.log)

**Comment by sherifabdlnaby** [comment] 2020-08-07 13:37
It looks like you uncommented the ElastAlert config in Kibana.yml without adding the plugin to the image, so Kibana fails to start because there is an unknown configuration.
```
## ElastAlert Plugin
elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030
```
Please comment this configuration.

**Comment by caotangdaiduong** [comment] 2020-08-09 07:48
I left the profiles completely defaults. I used Centos 8 and it worked.
It seems you don't have the recommended configurations: CPU, RAM, OS ?

**Comment by caotangdaiduong** [comment] 2020-08-09 09:12
How to change ssl for my domain example.com?
I have tried changing the DNS in setup / instances.yml and make cert, make restart, but not working
![image](https://user-images.githubusercontent.com/28684084/89728909-f9bc4b00-da5a-11ea-9f0b-c511d62d1549.png)

**Comment by sherifabdlnaby** [comment] 2020-08-16 10:07
Please head out to the [elasticsearch cert utility documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html) and change the script according to your needs

**Comment by sherifabdlnaby** [comment] 2020-08-18 22:29
Since the original problem of the issue is solved I am closing this one. ✌️

**Closed by sherifabdlnaby** 2020-08-18 22:29 UTC
Labels: bug
